// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	model "github.com/BellringerQuinn/blockchainNodeGateway/model"
	mock "github.com/stretchr/testify/mock"

	provider "github.com/BellringerQuinn/blockchainNodeGateway/provider"
)

// ProviderSelector is an autogenerated mock type for the ProviderSelector type
type ProviderSelector struct {
	mock.Mock
}

// ConstructRequest provides a mock function with given fields: params
func (_m *ProviderSelector) ConstructRequest(params model.Params) (*http.Request, provider.Provider) {
	ret := _m.Called(params)

	var r0 *http.Request
	var r1 provider.Provider
	if rf, ok := ret.Get(0).(func(model.Params) (*http.Request, provider.Provider)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(model.Params) *http.Request); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Params) provider.Provider); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Get(1).(provider.Provider)
	}

	return r0, r1
}

// DisableProviderForNetworkAndResource provides a mock function with given fields: _a0, params
func (_m *ProviderSelector) DisableProviderForNetworkAndResource(_a0 provider.Provider, params model.Params) {
	_m.Called(_a0, params)
}

type mockConstructorTestingTNewProviderSelector interface {
	mock.TestingT
	Cleanup(func())
}

// NewProviderSelector creates a new instance of ProviderSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProviderSelector(t mockConstructorTestingTNewProviderSelector) *ProviderSelector {
	mock := &ProviderSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
