// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	model "github.com/BellringerQuinn/blockchainNodeGateway/model"
	mock "github.com/stretchr/testify/mock"
)

// SelectorHelper is an autogenerated mock type for the SelectorHelper type
type SelectorHelper struct {
	mock.Mock
}

// SelectProvider provides a mock function with given fields: params
func (_m *SelectorHelper) SelectProvider(params model.Params) model.Provider {
	ret := _m.Called(params)

	var r0 model.Provider
	if rf, ok := ret.Get(0).(func(model.Params) model.Provider); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(model.Provider)
	}

	return r0
}

type mockConstructorTestingTNewSelectorHelper interface {
	mock.TestingT
	Cleanup(func())
}

// NewSelectorHelper creates a new instance of SelectorHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSelectorHelper(t mockConstructorTestingTNewSelectorHelper) *SelectorHelper {
	mock := &SelectorHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
